### ISSUE TITLE
Missing the LaunchRequestHandler defination

### ISSUE THREAD

**Issue by rsys-dinesh** [alexa-smart-properties/skill-sample-for-webrtc-asp#2]
https://github.com/alexa-smart-properties/skill-sample-for-webrtc-asp/blob/fad0db3766c41e334b0393c0bc440c79e8e999cf/lambda/custom/index.js#L300

**Comment by billykuo** [comment]
Thanks for reporting this. Launch handler is optional with this particular type of skill. I've removed the undefined handlers from the list.

**Comment by rsys-dinesh** [comment]
I've implemented the changes, but when executing in Lambda, I'm encountering a more generic error.

`{
    "errorType": "AskSdk.GenericRequestDispatcher Error",
    "errorMessage": "Unable to find a suitable request handler.",
    "name": "AskSdk.GenericRequestDispatcher Error",
    "stack": [
        "AskSdk.GenericRequestDispatcher Error: Unable to find a suitable request handler.",
        "    at createAskSdkError (/var/task/node_modules/ask-sdk-runtime/dist/util/AskSdkUtils.js:23:19)",
        "    at GenericRequestDispatcher.dispatchRequest (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:72:55)",
        "    at async GenericRequestDispatcher.dispatch (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:45:22)",
        "    at async CustomSkill.invoke (/var/task/node_modules/ask-sdk-core/dist/skill/CustomSkill.js:68:26)"
    ]
}`
